### ISSUE TITLE
World readable, admin-only editing

### ISSUE THREAD

**Issue by bmann** [rsc/tiddly#2]
I'm looking at how to make the wiki no-login-required to read it, while still admin for editing.

I poked around app.yaml definitions a bit https://cloud.google.com/appengine/docs/go/config/appref

From reading that, it looks like only URL regexs are supported, and I'm guessing since TW uses anchors, this might be a little tough? Any help is appreciated.

(Even with Google Cloud / App Engine etc. yak shaving, this was a slick and simple way to get TW running on a server. Thank you!)

**Comment by rsc** [comment]
Hi. I started a reply but figured it would be good to record for posterity, so I tweaked the code a bit and added a comment. See the diff in https://github.com/rsc/tiddly/commit/8f9145ac183e374eb95d90a73be4d5f38534ec47.

The short answer is that yes you can make that work on the app side, but then TiddlyWiki's sync logic is going to need some help; otherwise viewers just get a bunch of pop-ups telling them they can't save changes, even for things like updating the story list.

**Comment by rsc** [comment]
I should add, my test instance at tiddlywiki-gae.appspot.com is running in this mode right now (and likely will until the next time I need to try something), so if you want to see what the pop-ups look like, load that page and poke around.

![screen shot 2017-01-03 at 12 11 57 pm](https://cloud.githubusercontent.com/assets/104030/21615994/da974ea0-d1ad-11e6-9250-928fe63850cc.png)

**Comment by bmann** [comment]
Thanks @rsc! Yeah, the version of TW that I have running on CouchDB / Cloudant has similarly ugly popups. That's something that should get done on the TW side, at the very least for the StoryList.

Or have an option to suppress those error messages.

Not quite the same thing, but this is a related issue Jermolene/TiddlyWiki5/issues/532

I'll look for error message suppression.
